### ISSUE TITLE
Supplier-* must be replaced by TV "Suppliers", holding subpaths

### ISSUE THREAD

**Issue by ArjanLoeffen** [Imvertor/Imvertor-Maven#21]
Supplier-project, -name, -release should be replaced by TV "Suppliers", holding subpaths. Subpaths may be separated by ; and several tagged values Supplier may be specified.

The current approach should be supported for some time, but a method of safely phasing out this approach should be devised.

**Comment by ArjanLoeffen** [comment]
Thies, Robert, Jullie mening?

**Comment by melsk-r** [comment]
So you would like to remove the tagged values
* Supplier-project
* Supplier-name
* Supplier-release

and introduce the new tagged-value 'Suppliers'. 
That tagged-value may occur more than once and the value consists of the concatenation of the current tagged values. So in stead of the separated tagged-values with the values:
* SIM;UGM;UGM
* RGBZ;ZTC;RSGB
* 20180525;20180525;20180501

you get 3 tagged values 'Suppliers' with the values:
* SIM RGBZ 20180525
* UGM ZTC 20180525
* UGM RSGB 20180501

Advantage of this change is you don't have to interprete the tagged values anymore to see which are the supplier models. I believe the above lists proves this assumption.

Disadvantage however is everybody needs to comply to a strong namingconvention so the code is able to break the new names into the 3 parts itself. A name like 'UGM UGM RSGB 03_00_01 20180501' should not be allowed anymore. Or do you think this won't be a problem at all?

If we decide to implement the new tagged-value a Warning should be generated for a fixed period after introduction telling the user to replace the 3 tagged values by the new one. After that period the lack of the new Tagged value and the presence of the old once should result in an Error forcing the user to create the new tagged value or deleting the old onces (since the tagged values are optional).

**Comment by ThiesMesdag** [comment]
This is not an immediately necessary change for the Kadaster. But in the first reading I was expecting something like "cdmkad / CDMKAD / 20190901" like on the dashboard (https://imvertor.armatiek.nl/imvertor-executor/dashboard/apps). 

A warning is indeed useful for the transition period. 

Multiple supplier TV is more convenient so:
Supplier = cdmkad / CDMKAD / 20190901
Supplier = imkad / IMAST / 20190901

The old supplier can also be converted by Imvertor to this notation (probably already happens) and then the change is backwards compatible.

**Comment by melsk-r** [comment]
Not immediately necessary for VNG too.
