### ISSUE TITLE
Extra dash in definitie veld leidt tot negeren definitie maar niet tot foutmelding.

### ISSUE THREAD

**Issue by wilkoquak** [Imvertor/Imvertor-Maven#508]
![afbeelding](https://github.com/Imvertor/Imvertor-Maven/assets/2814052/f218602e-5a54-4806-833e-88576db8da8e)

**Comment by ArjanLoeffen** [comment]
Wat wil je dat de regel is?

Hou er rekening mee dat ook in de lopende tekst twee liggende streepjes een rol kunnen spelen. Een mogelijke regel is:

**Begin van de regel + twee of meer streepjes + categorie-woord zoals "Definitie" + twee of meer liggende streepjes + regeleinde**

**Comment by wilkoquak** [comment]
Een typefout als deze is snel gemaakt en ik zou vooral blij zijn met een waarschuwing die zegt dat er een deel van het notes veld genegeerd wordt: in het geval hierboven verdween de hele definitie in het niets. Verder vind ik een strakke definite prima:

**Begin van de regel + twee streepjes + categorie-woord zoals "Definitie" + twee streepjes + regeleinde**

Zolang ik maar een melding krijg dat de tekst genegeerd wordt of dat de tekst in de catalogus terechtkomt zodat ik door het checken op meldingen + het visueel controleren op de correctheid van de output kan weten of alles goed is overgekomen.

**Comment by ArjanLoeffen** [comment]
Aha, wacht even. Wanneer documentatie wordt samengevoegd vanuit supplier models wordt een "separator" sequence opgenomen in het notes field. Dat heeft de vorm van "drie of meer streepjes". Alles achter die streepjes wordt weggelaten uit de verwerking. Dat is by design. Dat kun je ook zelf opnemen in je notes field, zodat je wat aantekeningen daarin kwijt kan.

Wat we kunnen doen voor Geonovum is die separator veranderen (`documentation-separator-pattern`). Bijvoorbeeld in drie of meer = tekens. Daarmee ontwijk je dit soort problemen.

Als je nooit in een notes field iets wilt opnemen wat je niet ook in de verwerking wilt terugzien, kun je besluiten een echt totaal uniek patroon te configureren. Dus iets als "xyxyxyxyx" of zo.

@wilkoquak graag je mening.

**Comment by wilkoquak** [comment]
Aha, nu snap ik het. Met mijn typefout heb ik een feature geactiveerd die ik niet kende (maar ik nu wel ga gebruiken). Hmm lastig, als je dit configureerbaar gaat maken dan gaan mensen weer eigen keuzes maken waar ik ook weer niet blij van wordt.  Nu ik dit weet kan ik er denk ik wel mee leven en ga het bug report sluiten.
